apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
  labels:
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom: 
      - secretRef:
          name: pod-secret