apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #deployment labels
  labels:
    project: roboshop
    purpose: deployment-demo
spec:
  replicas: 2
  #these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      purpose: deployment-demo
  #this is pod definition
  template:
    metadata:
      labels:
        project: roboshop
        purpose: deployment-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest